name: icefishingderby
description: A new Flutter application.
publish_to: none
version: 1.0.0+1
environment:
  sdk: ">=2.3.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  auto_route: ^0.6.9
  awesome_loader: ^0.0.3
  flutter_custom_clippers: ^1.1.1
  flutter_screenutil: ^1.0.2
  google_fonts:
  get_it: ^6.0.0
  font_awesome_flutter: ^8.5.0
  flutter_signin_button: ^1.1.0
  logger: ^0.9.2
  stacked: ^2.1.0
  stacked_services: ^0.5.4+2
  responsive_builder: ^0.2.0+2
  equatable: ^1.2.4
  sign_button: ^1.0.2
  flutter_icons: ^1.0.0+1
  font_awesome: ^5.10.1
  injectable: ^1.0.7
  carousel_slider: ^3.0.0
  firebase_core:
  firebase_auth:
  

  firebase_storage:
  google_sign_in: ^4.5.1
  sign_in_with_apple: ^2.5.2
  crypto:
  flutter_credit_card: ^0.1.4
  flutter_barcode_scanner: ^2.0.0
  image_picker: 
  qr_flutter: ^3.2.0
  multi_sort: ^3.0.0
  flutter_launcher_icons: ^0.9.0  

  #for Android and iOS
  stripe_payment: ^1.0.7
  cloud_firestore:
  stripe_sdk:

dev_dependencies:
  flutter_test:
    sdk: flutter
   

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/derby-logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/logos/
    - assets/fish/
    - assets/icons/